import house1 from '../assets/house1.jpg';
import house2 from '../assets/house2.webp';

export const properties = [
  {
    id: 1,
    price: 300000,
    slug: 'seaside-villa',
    title: 'Seaside Villa',
    description: 'A beautiful villa by the sea.',
    image: house1,
    isPrivate: false,
    isFrozen: false,
  },
  {
    id: 2,
    price: 500000,
    slug: 'secret-mountain-cabin',
    title: 'Secret Mountain Cabin',
    description: 'Hidden gem in the mountains.',
    image: house2,
    isPrivate: true,
    isFrozen: true,
  },
    {
    id: 3,
    price: 750000,
    slug: 'urban-loft-apartment',
    title: 'Urban Loft Apartment',
    description: 'Stylish loft in the heart of the city.',
    image: house1,
    isPrivate: false,
    isFrozen: false,
  },
  {
    id: 4,
    price: 950000,
    slug: 'beachside-villa',
    title: 'Beachside Villa',
    description: 'Oceanfront villa with stunning sunset views.',
    image: house2,
    isPrivate: true,
    isFrozen: false,
  },
  {
    id: 5,
    price: 400000,
    slug: 'country-cottage',
    title: 'Country Cottage',
    description: 'Charming cottage surrounded by nature.',
    image: house1,
    isPrivate: false,
    isFrozen: true,
  },
  {
    id: 6,
    price: 620000,
    slug: 'modern-townhouse',
    title: 'Modern Townhouse',
    description: 'Newly built townhouse in a quiet neighborhood.',
    image: house2,
    isPrivate: false,
    isFrozen: false,
  },
  {
    id: 7,
    price: 820000,
    slug: 'desert-retreat',
    title: 'Desert Retreat',
    description: 'Peaceful home in the middle of the desert.',
    image: house1,
    isPrivate: true,
    isFrozen: true,
  },
  {
    id: 8,
    price: 1000000,
    slug: 'lakefront-mansion',
    title: 'Lakefront Mansion',
    description: 'Luxurious mansion with private lake access.',
    image: house2,
    isPrivate: false,
    isFrozen: false,
  },
  {
    id: 9,
    price: 550000,
    slug: 'forest-cabin',
    title: 'Forest Cabin',
    description: 'Cozy cabin deep in the woods.',
    image: house1,
    isPrivate: true,
    isFrozen: false,
  },
  {
    id: 10,
    price: 460000,
    slug: 'suburban-home',
    title: 'Suburban Home',
    description: 'Family-friendly home near schools and parks.',
    image: house2,
    isPrivate: false,
    isFrozen: false,
  },
  {
    id: 11,
    price: 720000,
    slug: 'cliffside-residence',
    title: 'Cliffside Residence',
    description: 'Breathtaking views from the cliff edge.',
    image: house1,
    isPrivate: true,
    isFrozen: true,
  },
  {
    id: 12,
    price: 310000,
    slug: 'downtown-condo',
    title: 'Downtown Condo',
    description: 'Compact condo in a central location.',
    image: house2,
    isPrivate: false,
    isFrozen: true,
  },
];

export function getProps(){
    return properties;
};
export function getProperty(slug: string) {
  return properties.find((p) => p.slug === slug) || null;
}
